version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: invoices_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./server
    container_name: nest_backend
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/invoices_db?schema=public
      JWT_SECRET: "supersecret"

  frontend:
    build: ./client
    container_name: react_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"  

volumes:
  pgdata:
