version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: nestjs_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: invoices_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: